var chat_names = {}
chat_names['O  Município'] = '#ef476f'
chat_names['Gazeta  do  Povo  Local'] = '#f36a6d'
chat_names['UOL  Tilt'] = '#f78c6b'
chat_names['Correio  Sabiá'] = '#fbaf69'
chat_names['O  Mirante  Joinville'] = '#ffd166'
chat_names['Jornal  do  Comércio'] = '#e0d26e'
chat_names['GZH'] = '#c1d375'
chat_names['Gazeta  do  Povo'] = '#a2d47c'
chat_names['Tribuna  do  Paraná'] = '#83d483'
chat_names['O  Estado  de  S.  Paulo'] = '#45d592'
chat_names['O  Município  Joinville'] = '#06d6a0'
chat_names['Matinal'] = '#09c3a5'
chat_names['The  Intercept  Brasil'] = '#0cb0a9'
chat_names['Pública'] = '#0f9dae'
chat_names['UOL  Economia+'] = '#118ab2'
chat_names['Aos  Fatos'] = '#0f7799'
chat_names['Seu  Panorama'] = '#0c637f'
chat_names['GZH  Coronavirus'] = '#073b4c'

chat_names['O Município'] = '#ef476f'
chat_names['Gazeta do Povo Local'] = '#f36a6d'
chat_names['UOL Tilt'] = '#f78c6b'
chat_names['Correio Sabiá'] = '#fbaf69'
chat_names['O Mirante Joinville'] = '#ffd166'
chat_names['Jornal do Comércio'] = '#e0d26e'
chat_names['GZH'] = '#c1d375'
chat_names['Gazeta do Povo'] = '#a2d47c'
chat_names['Tribuna do Paraná'] = '#83d483'
chat_names['O Estado de S. Paulo'] = '#45d592'
chat_names['O Município Joinville'] = '#06d6a0'
chat_names['Matinal'] = '#09c3a5'
chat_names['The Intercept Brasil'] = '#0cb0a9'
chat_names['Pública'] = '#0f9dae'
chat_names['UOL Economia+'] = '#118ab2'
chat_names['Aos Fatos'] = '#0f7799'
chat_names['Seu Panorama'] = '#0c637f'
chat_names['GZH Coronavirus'] = '#073b4c'



